### ISSUE TITLE
Can't open the web page with the default site 'http://localhost:5000' when debugging a webapi project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-dapr#111]
**OS:** Win10
**Build Version:** 20200827.4

**Repro Steps:**
1. Open a webapi project in VS Code.
2. F1 -> Dapr: Scaffold Dapr Tasks -> .NET Core Launch (web) -> Enter a Dapr ID 'app' for the application -> Enter the port '5000'.
3. Switch to the debug tab and change the configuration to '.NET Core Launch (web) with Dapr', then F5.
4. Check the opened web page. 

**Expect:**
The web page shows well with site 'http://localhost:5000/WeatherForecast'.
![image](https://user-images.githubusercontent.com/45614674/91541903-9c2b6800-e94f-11ea-9506-95650a02e65a.png)

**Actual:**
Can't open the web page with the site 'http://localhost:5000'.
![image](https://user-images.githubusercontent.com/45614674/91541580-1f988980-e94f-11ea-8ec1-4e12ccd7486d.png)

**More Info:**
The web page can be opened successfully after manually add the '/WeatherForecast' to the link.

**Comment by philliphoff** [comment]
@v-ruizh What's the behavior when you run the non-Dapr-ized launch profile?  (On my machine, the browser opens to `http://localhost:5000`, which results in a `404`.)

The default .NET launch profile scaffolding doesn't automatically open the browser to a specific controller endpoint, in the case of a WebAPI project.  The Dapr scaffolding only copies the .NET launch profile, so it would be expected that it, also, doesn't open the browser to a specific controller endpoint.  However, if you explicitly set the profile's URL to open (e.g. set `serverReadyAction.uriFormat` to `%s/WeatherForecast`), when you invoke the Dapr scaffolding it will do the same.

It's a little strange for the .NET scaffolding to open the browser *at all* for WebAPI projects, since it would be difficult to know what the default controller endpoint would be, unless one were using something like Swagger and it's API browsing component.

**Comment by v-ruizh** [comment]
@philliphoff Yes, the result is a 404 if run the non-Dapr-ized launch profile. 

Thanks for your guidance. The webpage opens well after setting serverReadyAction.uriFormat to %s/WeatherForecast for .NET Core 3.1 project. For .NET Core 2.1 project, we should set serverReadyAction.uriFormat to %s/api/values manually. 

I found the webpage for webapi project can open successfully in VS. Personally, it will be better if adding this setting as the default setting in VS Code, so I logged this issue. You can ignore this issue if it is difficult to implementation.

**Comment by philliphoff** [comment]
@v-ruizh I agree that'd it'd be nice to have consistency in the behavior of newly-created projects between VS and VS Code.  However, VS has the benefit of assets for both the project itself and the debug launch being scaffolded at the same time (i.e. project creation time), so the scaffolding "knows" what URL makes sense for the browser.  Scaffolding for VS Code happens in two places, the project assets are created via `dotnet new` and then the debug launch assets are later created by a separate (OmniSharp) extension within VS Code.  That extension may not be able to (easily) determine a reasonable URL for the browser.  (That said, there is a [long-standing issue](https://github.com/OmniSharp/omnisharp-vscode/issues/2868) to use the project-scaffolded launchSettings.json to derive the URL in VS Code.  It may be worth adding your support to that issue in the hopes that it gets resolved.)

In any case, I don't think we want the Dapr extension making that decision on its own when it adds its scaffolding. The intent is for Dapr to simply be added in the background without changing the underlying behavior of the .NET application, so any decision about which URL to launch should (in my opinion) come from the existing .NET debug launch configuration.
