### ISSUE TITLE
[Suggestion] Add a "Report an issue" button in the notification

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-dapr#122]
**OS:** All
**Build Version:** 20200902.2

**Repro Steps:**
1. Create a new .NET Web API application by "dotnet new webapi --no-https --name netwebapp".
2. Open the application in VS Code --> Select "Dapr: Scaffold Dapr Tasks" from Command Palette --> Select ".NET Core Launch (web)" when asked to select a configuration --> Enter an application ID --> Enter an application port.     
4. Debug with ".NET Core Launch (web) with Dapr".
5. Right click the running application --> Select "Invoke (GET) Application Method" --> Enter an invalid appliacation method.
6. Check the result.

**Actual:**
There is no "Report an issue" button.
![image](https://user-images.githubusercontent.com/62053665/92090671-4567d780-ee02-11ea-8fb9-3a4d5c1b68c8.png)

**Suggestion:**
Add a "Report an issue" button in the notification.

**More Info:**
This issue also reproduces for node.js project.

**Comment by philliphoff** [comment]
@v-mengwe It was a conscious choice *not* to have the "Report an issue" button for these particular commands, as the thought was that failures were most likely due to the user's application itself and not the extension.  That is, the 404 error above was returned by the application because no such method name exists, not because the extension invoked the application in an improper manner.  As there isn't a good way to determine valid endpoints for the application (ignoring specifications like Swagger, etc.), the extension cannot validate that the user has entered a valid method name; the best we can do is attempt it and return the result (which may be a failure).  Adding a button to report the issue would likely not be actionable (by us).

I'll close this for now, but if you have suggestions for ways we might otherwise validate the method names or better inform users of failures, let me know.

**Comment by v-mengwe** [comment]
Got it, thanks for your sharing.
