### ISSUE TITLE
dapr-debug task blocks if appPort is not specified

### ISSUE THREAD

**Issue by databasedav** [microsoft/vscode-dapr#93]
- vscode 1.44.2
- dapr 0.6.0
- vscode dapr 0.2.1
- vscode python 2020.4.74986

Reproduction steps:
- clone the python sdk repo
- open `example.py` in the repo
- click `create a launch.json file` in the vscode activity bar and choose `Python File`
- run `Dapr: Scaffold Dapr Tasks` on the `Python: Current File` config that was created; use default app id and port
- in the generated `tasks.json`, comment the line `"appPort": 8000,`
- select `example.py` in vscode and run the generated `Python: Current File with Dapr` config

I would expect the python file to be run after `daprd` is finished but based on the vscode ui, it looks like the task is blocking. Uncommenting the `"appPort": 8000,` line allows the python file to run but, for example, the `example.py` in the python sdk isn't a service that is invokable by dapr and simply houses a dapr client, so the `appPort` shouldn't be required.

**Comment by philliphoff** [comment]
@databasedav I believe this is the same issue as #89, where the problem matcher doesn't handle the case where `daprd` does not wait for the application to start because it was not given an `appPort`, which is the case for non-web-applications.  I expect that that workaround will work here, too.  Please let me know if it does not.

**Comment by databasedav** [comment]
@philliphoff the work around in #89 works for me. Thanks!
